-- V10__leave.sql — 연차 부여 / 휴가 신청 (설계서 6.5, 7.2)
--
-- 부여(GRANT)와 사용(REQ)을 나눈다. 잔여일수는 컬럼이 아니라 GRANT_DAYS - USED_DAYS 로 파생된다.

CREATE TABLE TB_LEAVE_GRANT (
    GRANT_ID    NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    EMP_ID      NUMBER       NOT NULL,
    YEAR_NO     NUMBER(4)    NOT NULL,             -- 부여 연도
    GRANT_DAYS  NUMBER(4, 1) NOT NULL,
    USED_DAYS   NUMBER(4, 1) DEFAULT 0 NOT NULL,
    EXPIRE_DT   DATE         NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_LEAVE_GRANT_EMP FOREIGN KEY (EMP_ID) REFERENCES TB_EMP(EMP_ID),
    -- 같은 직원에게 같은 연도 연차를 두 번 부여하지 않는다. annualLeaveGrantJob(Phase 7)이
    -- 재실행돼도 이 제약이 중복 부여를 막는다 — 배치 멱등성의 방어선을 코드가 아니라 스키마에 둔다.
    CONSTRAINT UQ_LEAVE_GRANT UNIQUE (EMP_ID, YEAR_NO),
    CONSTRAINT CK_LEAVE_GRANT_DAYS CHECK (GRANT_DAYS >= 0 AND USED_DAYS >= 0 AND USED_DAYS <= GRANT_DAYS)
);

COMMENT ON TABLE TB_LEAVE_GRANT IS '연차 부여. 잔여일수는 GRANT_DAYS - USED_DAYS 파생값';
COMMENT ON COLUMN TB_LEAVE_GRANT.USED_DAYS IS '승인된 연차 사용일수 합계. CK 제약이 부여일수 초과를 막는다';

-- UQ_LEAVE_GRANT(EMP_ID, YEAR_NO)가 이미 같은 컬럼 인덱스를 만들므로 별도 인덱스는 두지 않는다(ORA-01408).
-- 직원별 조회도 이 유니크 인덱스의 선두 컬럼(EMP_ID)으로 커버된다.

CREATE TABLE TB_LEAVE_REQ (
    LEAVE_REQ_ID    NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    EMP_ID          NUMBER       NOT NULL,
    LEAVE_TYPE_CD   VARCHAR2(30) NOT NULL,         -- CD:LEAVE_TYPE
    START_DT        DATE         NOT NULL,
    END_DT          DATE         NOT NULL,
    DAYS            NUMBER(4, 1) NOT NULL,
    STATUS_CD       VARCHAR2(30) NOT NULL,         -- CD:LEAVE_STATUS (REQUESTED/APPROVED/REJECTED/CANCELED)
    APPROVER_EMP_ID NUMBER,
    RSN_TXT         VARCHAR2(400),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_LEAVE_REQ_EMP FOREIGN KEY (EMP_ID) REFERENCES TB_EMP(EMP_ID),
    CONSTRAINT FK_LEAVE_REQ_APPROVER FOREIGN KEY (APPROVER_EMP_ID) REFERENCES TB_EMP(EMP_ID),
    CONSTRAINT CK_LEAVE_REQ_PERIOD CHECK (START_DT <= END_DT),
    CONSTRAINT CK_LEAVE_REQ_DAYS CHECK (DAYS > 0),
    CONSTRAINT CK_LEAVE_REQ_STATUS CHECK (STATUS_CD IN ('REQUESTED', 'APPROVED', 'REJECTED', 'CANCELED'))
);

COMMENT ON TABLE TB_LEAVE_REQ IS '휴가 신청. 연차 차감은 승인(APPROVED) 시점에 TB_LEAVE_GRANT.USED_DAYS로 반영';

CREATE INDEX IX_LEAVE_REQ_EMP ON TB_LEAVE_REQ(EMP_ID, START_DT DESC);

INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('LEAVE_TYPE',   '휴가유형', NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('LEAVE_STATUS', '휴가신청상태', NULL, 'SYSTEM');

-- 연차 차감 여부(ANNUAL만 차감)는 여기 두지 않는다. ATTR1은 외부 시스템 코드 매핑 슬롯이고(설계서 9.6),
-- 차감 여부는 매핑이 아니라 업무 규칙이다 — LeaveType enum이 갖는다 (규칙은 도메인에).
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LEAVE_TYPE', 'ANNUAL',    '연차',     1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LEAVE_TYPE', 'SICK',      '병가',     2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LEAVE_TYPE', 'CONGRAT',   '경조사',   3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LEAVE_TYPE', 'OFFICIAL',  '공가',     4, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LEAVE_TYPE', 'UNPAID',    '무급휴가', 5, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LEAVE_STATUS', 'REQUESTED', '신청', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LEAVE_STATUS', 'APPROVED',  '승인', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LEAVE_STATUS', 'REJECTED',  '반려', 3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LEAVE_STATUS', 'CANCELED',  '취소', 4, 'SYSTEM');
