-- V12__eligibility.sql — 자격·교육·보증·제재 + 모집자격 입력 테이블 (설계서 5.4, 6.4, 6.5)
--
-- 이 테이블들이 RecruitEligibilityService.evaluate(agentId, asOfDate)의 입력이다. 판정은 순수 함수라
-- 여기 데이터와 기준일만으로 결과가 정해지고, 전이는 AgentEligibilityReconciler가 별도로 집행한다(설계서 5.4 v1.6).

-- 판매자격 (종목별). 종목 하나당 한 행 (UQ).
CREATE TABLE TB_AGENT_LICENSE (
    LICENSE_ID      NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    AGENT_ID        NUMBER       NOT NULL,
    LICENSE_TYPE_CD VARCHAR2(30) NOT NULL,          -- CD:LICENSE_TYPE (LIFE/NONLIFE/THIRD/VARIABLE)
    LICENSE_NO      VARCHAR2(30),
    EXAM_PASS_DT    DATE,
    REG_DT          DATE,
    STATUS_CD       VARCHAR2(30) NOT NULL,          -- CD:LICENSE_STATUS (VALID/SUSPENDED/REVOKED)
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_LIC_AGENT FOREIGN KEY (AGENT_ID) REFERENCES TB_AGENT(AGENT_ID),
    CONSTRAINT UQ_LIC UNIQUE (AGENT_ID, LICENSE_TYPE_CD)
);
CREATE INDEX IX_LIC_AGENT ON TB_AGENT_LICENSE(AGENT_ID);

-- 협회 등록/말소 이력.
CREATE TABLE TB_ASSOC_REG (
    ASSOC_REG_ID   NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    AGENT_ID       NUMBER       NOT NULL,
    ASSOC_CD       VARCHAR2(30) NOT NULL,           -- CD:ASSOC (LIFE_ASSOC/NONLIFE_ASSOC)
    ASSOC_REG_NO   VARCHAR2(50),
    REG_DT         DATE,
    DEREG_DT       DATE,
    DEREG_RSN_CD   VARCHAR2(30),
    STATUS_CD      VARCHAR2(30) NOT NULL,           -- CD:ASSOC_REG_STATUS (REGISTERED/DEREGISTERED)
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_ASSOC_AGENT FOREIGN KEY (AGENT_ID) REFERENCES TB_AGENT(AGENT_ID)
);
CREATE INDEX IX_ASSOC_AGENT ON TB_ASSOC_REG(AGENT_ID, ASSOC_CD);

-- 교차모집 등록.
CREATE TABLE TB_CROSS_SELL_REG (
    CROSS_SELL_ID  NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    AGENT_ID       NUMBER       NOT NULL,
    TARGET_LINE_CD VARCHAR2(30) NOT NULL,           -- CD:LICENSE_TYPE (교차 대상 종목)
    PARTNER_COMPANY_NM VARCHAR2(100),
    REG_DT         DATE,
    DEREG_DT       DATE,
    STATUS_CD      VARCHAR2(30) NOT NULL,           -- CD:CROSS_SELL_STATUS
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_XSELL_AGENT FOREIGN KEY (AGENT_ID) REFERENCES TB_AGENT(AGENT_ID)
);
CREATE INDEX IX_XSELL_AGENT ON TB_CROSS_SELL_REG(AGENT_ID);

-- 설계사 교육 이수 이력. NEXT_DUE_DT = COMPLETE_DT + 주기(정책값, 등록 시 자동계산).
CREATE TABLE TB_AGENT_EDU (
    AGENT_EDU_ID  NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    AGENT_ID      NUMBER       NOT NULL,
    EDU_TYPE_CD   VARCHAR2(30) NOT NULL,            -- CD:EDU_TYPE (REG/CONTINUING/VARIABLE/COMPLIANCE)
    EDU_NM        VARCHAR2(200) NOT NULL,
    COMPLETE_DT   DATE         NOT NULL,
    EDU_HOURS     NUMBER(5,1)  NOT NULL,
    PROVIDER_NM   VARCHAR2(100),
    NEXT_DUE_DT   DATE,                             -- 다음 이수기한 (보수교육에만 의미)
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_AEDU_AGENT FOREIGN KEY (AGENT_ID) REFERENCES TB_AGENT(AGENT_ID)
);
-- "이 설계사의 보수교육 최신 NEXT_DUE_DT" 조회 경로 (판정의 보수교육 게이트).
CREATE INDEX IX_AEDU_AGENT_DUE ON TB_AGENT_EDU(AGENT_ID, EDU_TYPE_CD, NEXT_DUE_DT);

-- 교육 정책 (교육유형별 주기/이수시간/필수여부). 등록 시 이수시간 검증·기한 계산의 참조.
CREATE TABLE TB_EDU_POLICY (
    EDU_POLICY_ID   NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    EDU_TYPE_CD     VARCHAR2(30) NOT NULL,
    CYCLE_MONTHS    NUMBER(3),                      -- 이수 주기(개월). 보수교육 기본 24
    MIN_HOURS       NUMBER(5,1)  NOT NULL,
    MANDATORY_YN    CHAR(1) DEFAULT 'Y' NOT NULL,
    APPLY_CHANNEL_CD VARCHAR2(30),                  -- null = 전 채널
    VALID_FROM_DT   DATE DEFAULT DATE '1900-01-01' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT CK_EDUPOL_MANDATORY CHECK (MANDATORY_YN IN ('Y', 'N'))
);
CREATE INDEX IX_EDUPOL_TYPE ON TB_EDU_POLICY(EDU_TYPE_CD, VALID_FROM_DT);

-- 재정보증. 유효 보증금액 합산이 MIN_GRNT_AMT 이상이어야 신계약 모집 가능(설계서 5.4 v1.6).
CREATE TABLE TB_FIN_GUARANTEE (
    GRNT_ID       NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    AGENT_ID      NUMBER        NOT NULL,
    GRNT_TYPE_CD  VARCHAR2(30)  NOT NULL,           -- CD:GRNT_TYPE (SURETY_INS/DEPOSIT/PERSONAL)
    GRNT_AMT      NUMBER(15)    NOT NULL,
    ISSUER_NM     VARCHAR2(100),
    POLICY_NO     VARCHAR2(50),
    START_DT      DATE          NOT NULL,
    END_DT        DATE          NOT NULL,
    STATUS_CD     VARCHAR2(30)  NOT NULL,           -- CD:GRNT_STATUS (ACTIVE/EXPIRED/CANCELED)
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_GRNT_AGENT FOREIGN KEY (AGENT_ID) REFERENCES TB_AGENT(AGENT_ID),
    CONSTRAINT CK_GRNT_PERIOD CHECK (START_DT <= END_DT)
);
CREATE INDEX IX_GRNT_AGENT ON TB_FIN_GUARANTEE(AGENT_ID, STATUS_CD, END_DT);

-- 제재/징계. RECRUIT_BLOCK_YN='Y'이고 기간 활성이면 모집정지 사유 → 자동 SUSPENDED(reconciler 경로).
CREATE TABLE TB_AGENT_SANCTION (
    SANCTION_ID     NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    AGENT_ID        NUMBER       NOT NULL,
    SANCTION_ORG_CD VARCHAR2(30) NOT NULL,          -- CD:SANCTION_ORG (FSS/ASSOC/INTERNAL)
    SANCTION_TYPE_CD VARCHAR2(30) NOT NULL,         -- CD:SANCTION_TYPE (RECRUIT_STOP/WARNING/FINE/DISMISS)
    START_DT        DATE         NOT NULL,
    END_DT          DATE,                           -- null = 무기한
    RSN_TXT         VARCHAR2(400),
    RECRUIT_BLOCK_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_SANC_AGENT FOREIGN KEY (AGENT_ID) REFERENCES TB_AGENT(AGENT_ID),
    CONSTRAINT CK_SANC_BLOCK CHECK (RECRUIT_BLOCK_YN IN ('Y', 'N'))
);
CREATE INDEX IX_SANC_AGENT ON TB_AGENT_SANCTION(AGENT_ID, RECRUIT_BLOCK_YN, END_DT);

-- 불완전판매 건. 제재로 이어질 수 있어 LINKED_SANCTION_ID로 연결한다.
CREATE TABLE TB_MISSELL_CASE (
    MISSELL_ID      NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    AGENT_ID        NUMBER       NOT NULL,
    CONTRACT_NO     VARCHAR2(50),
    CASE_TYPE_CD    VARCHAR2(30) NOT NULL,          -- CD:MISSELL_CASE_TYPE
    OCCUR_DT        DATE         NOT NULL,
    RESOLVE_DT      DATE,
    RESULT_CD       VARCHAR2(30),                   -- CD:MISSELL_RESULT
    LINKED_SANCTION_ID NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_MISSELL_AGENT FOREIGN KEY (AGENT_ID) REFERENCES TB_AGENT(AGENT_ID),
    CONSTRAINT FK_MISSELL_SANCTION FOREIGN KEY (LINKED_SANCTION_ID) REFERENCES TB_AGENT_SANCTION(SANCTION_ID)
);
CREATE INDEX IX_MISSELL_AGENT ON TB_MISSELL_CASE(AGENT_ID);

-- ── 공통코드 추가 (설계서 부록 A). LICENSE_STATUS/GRNT_STATUS/SANCTION_*/ASSOC/EDU_TYPE는 V2가 시드했다 ──
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('ASSOC_REG_STATUS', '협회등록상태', NULL, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ASSOC_REG_STATUS', 'REGISTERED',   '등록', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ASSOC_REG_STATUS', 'DEREGISTERED', '말소', 2, 'SYSTEM');

INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('CROSS_SELL_STATUS', '교차모집상태', NULL, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('CROSS_SELL_STATUS', 'REGISTERED',   '등록', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('CROSS_SELL_STATUS', 'DEREGISTERED', '말소', 2, 'SYSTEM');

INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('MISSELL_CASE_TYPE', '불완전판매유형', NULL, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('MISSELL_CASE_TYPE', 'COMPLAINT',   '민원',       1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('MISSELL_CASE_TYPE', 'INCOMPLETE',  '불완전판매', 2, 'SYSTEM');

INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('MISSELL_RESULT', '불완전판매결과', NULL, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('MISSELL_RESULT', 'CONFIRMED', '확정', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('MISSELL_RESULT', 'DISMISSED', '기각', 2, 'SYSTEM');

-- ── 교육 정책 시드 (설계서 6.5) ──
INSERT INTO TB_EDU_POLICY (EDU_TYPE_CD, CYCLE_MONTHS, MIN_HOURS, MANDATORY_YN, CREATED_BY)
VALUES ('REG',        NULL, 20, 'Y', 'SYSTEM');    -- 등록교육: 위촉 요건, 주기 없음
INSERT INTO TB_EDU_POLICY (EDU_TYPE_CD, CYCLE_MONTHS, MIN_HOURS, MANDATORY_YN, CREATED_BY)
VALUES ('CONTINUING', 24,   12, 'Y', 'SYSTEM');    -- 보수교육: 24개월 주기 (CONT_EDU_CYCLE_MONTHS와 정합)
INSERT INTO TB_EDU_POLICY (EDU_TYPE_CD, CYCLE_MONTHS, MIN_HOURS, MANDATORY_YN, CREATED_BY)
VALUES ('VARIABLE',   NULL, 8,  'N', 'SYSTEM');    -- 변액자격교육
INSERT INTO TB_EDU_POLICY (EDU_TYPE_CD, CYCLE_MONTHS, MIN_HOURS, MANDATORY_YN, CREATED_BY)
VALUES ('COMPLIANCE', NULL, 4,  'N', 'SYSTEM');    -- 완전판매교육

-- ── 정책값 추가 (설계서 5.4 v1.6): 재위촉 시 과거 등록교육 재사용 여부 ──
INSERT INTO TB_POLICY_CONFIG (POLICY_KEY, POLICY_VAL, VAL_TYPE_CD, DESC_TXT, CREATED_BY)
VALUES ('REG_EDU_REUSE_ON_REAPPOINT', 'Y', 'BOOLEAN', '재위촉 시 과거 등록교육 재사용 여부. ⚠️ 포트폴리오 가정값', 'SYSTEM');
