-- V13__integration.sql — 대외 연계 3계층의 공통 원천 (설계서 9장)
--
-- Outbox(이벤트 Push) · ChangeLog(변경분 Pull) · 구독자 · 전송이력. 세 계층이 이 두 원천에서 파생돼
-- 상호 대사가 가능하다(설계서 9.1). Phase 6에서 IntegrationRecorder 실구현이 여기에 쓰기 시작한다.

-- 트랜잭셔널 아웃박스. 기준정보 변경과 같은 트랜잭션에서 READY로 INSERT되고, relay가 집어 전송한다.
CREATE TABLE TB_IF_OUTBOX (
    EVENT_ID      NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    EVENT_UUID    VARCHAR2(36)  NOT NULL,          -- 멱등키. 재전송에도 동일
    AGG_TYPE      VARCHAR2(30)  NOT NULL,          -- PERSON/EMP/AGENT/ORG
    AGG_ID        NUMBER        NOT NULL,
    EVENT_TYPE    VARCHAR2(60)  NOT NULL,          -- 9.3 카탈로그 (agent.status.changed 등)
    PAYLOAD       CLOB          NOT NULL,
    STATUS_CD     VARCHAR2(10)  DEFAULT 'READY' NOT NULL, -- READY/SENT/FAILED/SKIPPED
    RETRY_CNT     NUMBER(3)     DEFAULT 0 NOT NULL,
    OCCURRED_AT   TIMESTAMP     DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    PUBLISHED_AT  TIMESTAMP,
    CONSTRAINT UQ_OUTBOX_UUID UNIQUE (EVENT_UUID),
    CONSTRAINT CK_OUTBOX_PAYLOAD_JSON CHECK (PAYLOAD IS JSON),
    CONSTRAINT CK_OUTBOX_STATUS CHECK (STATUS_CD IN ('READY', 'SENT', 'FAILED', 'SKIPPED'))
);
COMMENT ON TABLE TB_IF_OUTBOX IS '트랜잭셔널 아웃박스. 기준정보 변경과 한 트랜잭션 (설계서 9.2)';
-- relay가 READY를 EVENT_ID 순으로 집는 경로.
CREATE INDEX IX_OUTBOX_STATUS ON TB_IF_OUTBOX(STATUS_CD, EVENT_ID);
-- 순서 게이트: "같은 aggType+aggId에 미전송 선행이 있는가"를 싸게 판정하는 경로 (설계서 9.2 v1.6).
CREATE INDEX IX_OUTBOX_AGG ON TB_IF_OUTBOX(AGG_TYPE, AGG_ID, EVENT_ID);

-- 변경분 Pull용 변경 로그. SEQ_NO가 커서다. 전체 스냅샷(state-carried transfer)을 담아 순서 꼬임 없이 upsert 가능.
CREATE SEQUENCE SEQ_IF_CHANGE_LOG START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE TABLE TB_IF_CHANGE_LOG (
    SEQ_NO         NUMBER        PRIMARY KEY,       -- 전역 시퀀스 = Pull 커서
    AGG_TYPE       VARCHAR2(30)  NOT NULL,
    AGG_ID         NUMBER        NOT NULL,
    CHANGE_TYPE_CD VARCHAR2(10)  NOT NULL,          -- C/U/D
    CHANGED_AT     TIMESTAMP     DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    SNAPSHOT_JSON  CLOB          NOT NULL,
    CONSTRAINT CK_CHANGELOG_JSON CHECK (SNAPSHOT_JSON IS JSON),
    CONSTRAINT CK_CHANGELOG_TYPE CHECK (CHANGE_TYPE_CD IN ('C', 'U', 'D'))
);
COMMENT ON TABLE TB_IF_CHANGE_LOG IS 'Pull API 커서 대상. SEQ_NO가 커서, SNAPSHOT_JSON은 전체 상태 (설계서 9.4)';
-- Pull 커서: aggType별 SEQ_NO > cursor 키셋 페이징 경로.
CREATE INDEX IX_CHANGELOG_CURSOR ON TB_IF_CHANGE_LOG(AGG_TYPE, SEQ_NO);
-- 워터마크 지연(9.4 v1.6): CHANGED_AT < now - N초 필터 경로.
CREATE INDEX IX_CHANGELOG_WATERMARK ON TB_IF_CHANGE_LOG(CHANGED_AT);

-- 구독(연계 대상) 시스템.
CREATE TABLE TB_IF_SUBSCRIBER (
    SUBSCRIBER_ID   NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    SYSTEM_CD       VARCHAR2(30)  NOT NULL,
    SYSTEM_NM       VARCHAR2(100) NOT NULL,
    DELIVERY_TYPE_CD VARCHAR2(10) NOT NULL,         -- WEBHOOK/KAFKA/FILE/PULL
    ENDPOINT_URL    VARCHAR2(500),
    SECRET_ENC      VARCHAR2(256),                  -- 서명 시크릿 AES 암호문
    TOPIC_FILTER    CLOB,                           -- 관심 eventType 목록 JSON (null=전체)
    USE_YN          CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT UQ_SUBSCRIBER_CD UNIQUE (SYSTEM_CD),
    CONSTRAINT CK_SUBSCRIBER_DELIVERY CHECK (DELIVERY_TYPE_CD IN ('WEBHOOK', 'KAFKA', 'FILE', 'PULL')),
    CONSTRAINT CK_SUBSCRIBER_TOPIC_JSON CHECK (TOPIC_FILTER IS JSON)
);
COMMENT ON TABLE TB_IF_SUBSCRIBER IS '구독 시스템. TOPIC_FILTER로 관심 이벤트만 전송 (설계서 6.5)';

-- 전송 이력. 전송 시도마다 1행(성공·실패 모두, 설계서 9.2 v1.6).
CREATE TABLE TB_IF_SEND_LOG (
    SEND_LOG_ID   NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    EVENT_ID      NUMBER        NOT NULL,
    SYSTEM_CD     VARCHAR2(30)  NOT NULL,
    SEND_AT       TIMESTAMP     DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    HTTP_STATUS   NUMBER(5),
    RESULT_CD     VARCHAR2(10)  NOT NULL,           -- SUCCESS/FAIL
    RESP_BODY     CLOB,
    RETRY_NO      NUMBER(3)     DEFAULT 0 NOT NULL,
    CONSTRAINT FK_SENDLOG_EVENT FOREIGN KEY (EVENT_ID) REFERENCES TB_IF_OUTBOX(EVENT_ID)
);
CREATE INDEX IX_SENDLOG_EVENT ON TB_IF_SEND_LOG(EVENT_ID);

-- ── 정책값 (설계서 9.2·9.4 v1.6) ──
INSERT INTO TB_POLICY_CONFIG (POLICY_KEY, POLICY_VAL, VAL_TYPE_CD, DESC_TXT, CREATED_BY)
VALUES ('SYNC_WATERMARK_SECONDS', '5', 'INT', 'Pull 커서 워터마크 지연(초). 시퀀스 갭 함정 방지 (설계서 9.4)', 'SYSTEM');
INSERT INTO TB_POLICY_CONFIG (POLICY_KEY, POLICY_VAL, VAL_TYPE_CD, DESC_TXT, CREATED_BY)
VALUES ('OUTBOX_MAX_RETRY', '5', 'INT', 'Outbox 전송 재시도 한도. 초과 시 FAILED + 수동 재전송 (설계서 9.2)', 'SYSTEM');
