-- V2__common_code.sql — 공통코드 (설계서 6.5, 부록 A)
--
-- 시드가 이 파일에 함께 있는 이유: 공통코드 값은 코드가 의존하는 도메인 상수라 환경별로 달라지지 않는다.
-- 반대로 정책값(V3)은 환경별로 달라지므로 파일을 분리한다.

CREATE TABLE TB_CD_GRP (
    GRP_CD      VARCHAR2(30)  NOT NULL,
    GRP_NM      VARCHAR2(100) NOT NULL,
    DESC_TXT    VARCHAR2(400),
    USE_YN      CHAR(1)       DEFAULT 'Y' NOT NULL,
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY  VARCHAR2(50)  NOT NULL,
    UPDATED_AT  TIMESTAMP,
    UPDATED_BY  VARCHAR2(50),
    CONSTRAINT PK_CD_GRP PRIMARY KEY (GRP_CD),
    CONSTRAINT CK_CD_GRP_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

COMMENT ON TABLE TB_CD_GRP IS '공통코드 그룹';

CREATE TABLE TB_CD (
    GRP_CD      VARCHAR2(30)  NOT NULL,
    CD          VARCHAR2(30)  NOT NULL,
    CD_NM       VARCHAR2(100) NOT NULL,
    SORT_ORD    NUMBER(5)     DEFAULT 0 NOT NULL,
    USE_YN      CHAR(1)       DEFAULT 'Y' NOT NULL,
    -- 외부 코드 매핑 슬롯 (설계서 9.6). 예: ATTR1=수수료시스템 코드
    ATTR1       VARCHAR2(100),
    ATTR2       VARCHAR2(100),
    ATTR3       VARCHAR2(100),
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY  VARCHAR2(50)  NOT NULL,
    UPDATED_AT  TIMESTAMP,
    UPDATED_BY  VARCHAR2(50),
    CONSTRAINT PK_CD PRIMARY KEY (GRP_CD, CD),
    CONSTRAINT FK_CD_GRP FOREIGN KEY (GRP_CD) REFERENCES TB_CD_GRP(GRP_CD),
    CONSTRAINT CK_CD_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

COMMENT ON TABLE TB_CD IS '공통코드';
COMMENT ON COLUMN TB_CD.ATTR1 IS '외부 시스템 코드 매핑 슬롯 (설계서 9.6)';

CREATE INDEX IX_CD_GRP_SORT ON TB_CD(GRP_CD, SORT_ORD);

-- ── 부록 A: 공통코드 초기 데이터 ─────────────────────────────────────────

INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('ORG_TYPE',      '조직유형',      '본사/영업 조직 계층 구분', 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('EMP_TYPE',      '직원구분',      '근로계약 기반 인력 구분', 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('EMP_STATUS',    '재직상태',      NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('APPOINT_TYPE',  '발령유형',      NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('CHANNEL',       '설계사채널',    NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('AGENT_STATUS',  '위촉상태',      '설계사 위촉 상태머신 (설계서 5.3)', 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('TERM_RSN',      '해촉사유',      NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('LICENSE_TYPE',  '판매자격종목',  NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('LICENSE_STATUS','자격상태',      NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('EDU_TYPE',      '교육유형',      NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('GRNT_TYPE',     '재정보증유형',  NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('GRNT_STATUS',   '재정보증상태',  NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('SANCTION_ORG',  '제재기관',      NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('SANCTION_TYPE', '제재유형',      NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('ASSOC',         '협회',          NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('GENDER',        '성별',          NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('JOB_GRADE',     '직급',          '자유 확장 (부록 A)', 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('JOB_TITLE',     '직책',          '자유 확장 (부록 A)', 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('USER_TYPE',     '계정유형',      '사람 계정 / 연계용 시스템 계정', 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('USER_STATUS',   '계정상태',      NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('ACCESS_TYPE',   '개인정보접근유형', '설계서 10.2', 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ORG_TYPE', 'HQ_DEPT', '본사부서', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ORG_TYPE', 'REGION',  '지역단',   2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ORG_TYPE', 'BRANCH',  '지점',     3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ORG_TYPE', 'OFFICE',  '영업소',   4, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EMP_TYPE', 'REGULAR',       '정규직',       1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EMP_TYPE', 'CONTRACT',      '계약직',       2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EMP_TYPE', 'SALES_SUPPORT', '영업지원스탭', 3, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EMP_STATUS', 'ACTIVE',   '재직', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EMP_STATUS', 'ON_LEAVE', '휴직', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EMP_STATUS', 'RESIGNED', '퇴직', 3, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('APPOINT_TYPE', 'HIRE',       '입사', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('APPOINT_TYPE', 'PROMOTION',  '승진', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('APPOINT_TYPE', 'TRANSFER',   '전보', 3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('APPOINT_TYPE', 'CONCURRENT', '겸직', 4, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('APPOINT_TYPE', 'LEAVE',      '휴직', 5, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('APPOINT_TYPE', 'RETURN',     '복직', 6, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('APPOINT_TYPE', 'DISPATCH',   '파견', 7, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('APPOINT_TYPE', 'RESIGN',     '퇴직', 8, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('CHANNEL', 'FC',     '전속설계사',   1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('CHANNEL', 'TC',     '텔레마케팅',   2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('CHANNEL', 'GA',     '대리점소속',   3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('CHANNEL', 'BANCA',  '방카',         4, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('CHANNEL', 'DM',     '다이렉트',     5, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('AGENT_STATUS', 'CANDIDATE',     '후보등록',       1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('AGENT_STATUS', 'PENDING_ASSOC', '협회등록신청중', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('AGENT_STATUS', 'ACTIVE',        '위촉',           3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('AGENT_STATUS', 'SUSPENDED',     '모집정지',       4, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('AGENT_STATUS', 'TERMINATED',    '해촉',           5, 'SYSTEM');

-- ATTR1='Y' = 재위촉 금지 사유 (설계서 5.3 TERMINATED → CANDIDATE 전이 조건).
-- 상태머신이 이 플래그를 읽는다 — 사유코드를 코드에 하드코딩하지 않기 위한 슬롯.
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, ATTR1, CREATED_BY) VALUES ('TERM_RSN', 'SELF',         '자진',                 1, 'N', 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, ATTR1, CREATED_BY) VALUES ('TERM_RSN', 'COMPANY',      '회사해촉',             2, 'N', 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, ATTR1, CREATED_BY) VALUES ('TERM_RSN', 'DISCIPLINE',   '징계해촉(재위촉금지)', 3, 'Y', 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, ATTR1, CREATED_BY) VALUES ('TERM_RSN', 'TRANSFER_OUT', '타사이동',             4, 'N', 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LICENSE_TYPE', 'LIFE',     '생명보험', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LICENSE_TYPE', 'NONLIFE',  '손해보험', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LICENSE_TYPE', 'THIRD',    '제3보험', 3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LICENSE_TYPE', 'VARIABLE', '변액보험', 4, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LICENSE_STATUS', 'VALID',     '유효', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LICENSE_STATUS', 'SUSPENDED', '정지', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('LICENSE_STATUS', 'REVOKED',   '말소', 3, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EDU_TYPE', 'REG',        '등록교육',     1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EDU_TYPE', 'CONTINUING', '보수교육',     2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EDU_TYPE', 'VARIABLE',   '변액자격교육', 3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EDU_TYPE', 'COMPLIANCE', '완전판매교육', 4, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GRNT_TYPE', 'SURETY_INS', '보증보험', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GRNT_TYPE', 'DEPOSIT',    '공탁',     2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GRNT_TYPE', 'PERSONAL',   '인보증',   3, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GRNT_STATUS', 'ACTIVE',   '유효', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GRNT_STATUS', 'EXPIRED',  '만료', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GRNT_STATUS', 'CANCELED', '해지', 3, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('SANCTION_ORG', 'FSS',      '금융당국', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('SANCTION_ORG', 'ASSOC',    '협회',     2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('SANCTION_ORG', 'INTERNAL', '사내',     3, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('SANCTION_TYPE', 'RECRUIT_STOP', '모집정지', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('SANCTION_TYPE', 'WARNING',      '경고',     2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('SANCTION_TYPE', 'FINE',         '과태료',   3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('SANCTION_TYPE', 'DISMISS',      '해촉',     4, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ASSOC', 'LIFE_ASSOC',    '생명보험협회', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ASSOC', 'NONLIFE_ASSOC', '손해보험협회', 2, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GENDER', 'M', '남', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GENDER', 'F', '여', 2, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('JOB_GRADE', 'STAFF',   '사원', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('JOB_GRADE', 'SENIOR',  '대리', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('JOB_GRADE', 'MANAGER', '과장', 3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('JOB_GRADE', 'DEPUTY',  '차장', 4, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('JOB_GRADE', 'GENERAL', '부장', 5, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('JOB_TITLE', 'TEAM_LEADER',   '팀장',     1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('JOB_TITLE', 'BRANCH_MGR',    '지점장',   2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('JOB_TITLE', 'OFFICE_MGR',    '영업소장', 3, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('USER_TYPE', 'HUMAN',  '사람',      1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('USER_TYPE', 'SYSTEM', '시스템계정', 2, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('USER_STATUS', 'ACTIVE',   '정상', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('USER_STATUS', 'LOCKED',   '잠금', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('USER_STATUS', 'DISABLED', '사용중지', 3, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ACCESS_TYPE', 'VIEW',    '조회',   1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ACCESS_TYPE', 'DECRYPT', '복호화', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ACCESS_TYPE', 'EXPORT',  '내보내기', 3, 'SYSTEM');
