-- V4__auth.sql — 계정/역할/권한 + 개인정보 접근로그 (설계서 6.5, 10.1, 10.2)

CREATE TABLE TB_USER (
    USER_ID        NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    LOGIN_ID       VARCHAR2(50)  NOT NULL,
    PWD_HASH       VARCHAR2(100),                  -- BCrypt. SYSTEM 계정은 비밀번호가 없어 NULL 허용
    -- 인물 연결. TB_PERSON은 Phase 2에서 만들어지므로 FK는 그때 추가한다.
    PERSON_ID      NUMBER,
    USER_TYPE_CD   VARCHAR2(10)  NOT NULL,         -- CD:USER_TYPE (HUMAN/SYSTEM)
    STATUS_CD      VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,  -- CD:USER_STATUS
    -- 로그인 연속 실패 잠금 (설계서 10.1, 임계값은 정책값 LOGIN_FAIL_LOCK_CNT)
    LOGIN_FAIL_CNT NUMBER(3)     DEFAULT 0 NOT NULL,
    LOCKED_AT      TIMESTAMP,
    LAST_LOGIN_AT  TIMESTAMP,
    PWD_CHANGED_AT TIMESTAMP,
    CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     VARCHAR2(50)  NOT NULL,
    UPDATED_AT     TIMESTAMP,
    UPDATED_BY     VARCHAR2(50),
    CONSTRAINT UQ_USER_LOGIN_ID UNIQUE (LOGIN_ID)
);

COMMENT ON TABLE TB_USER IS '계정 (설계서 6.5)';
COMMENT ON COLUMN TB_USER.PERSON_ID IS 'TB_PERSON 참조. FK는 Phase 2에서 추가';
COMMENT ON COLUMN TB_USER.PWD_HASH IS 'BCrypt 해시. SYSTEM 계정은 NULL';

CREATE INDEX IX_USER_PERSON ON TB_USER(PERSON_ID);

CREATE TABLE TB_ROLE (
    ROLE_CD    VARCHAR2(30)  NOT NULL,
    ROLE_NM    VARCHAR2(100) NOT NULL,
    DESC_TXT   VARCHAR2(400),
    CREATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(50)  NOT NULL,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_CD)
);

COMMENT ON TABLE TB_ROLE IS '역할 (설계서 10.1)';

CREATE TABLE TB_USER_ROLE (
    USER_ID    NUMBER       NOT NULL,
    ROLE_CD    VARCHAR2(30) NOT NULL,
    CREATED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ID, ROLE_CD),
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID),
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_CD) REFERENCES TB_ROLE(ROLE_CD)
);

CREATE TABLE TB_ROLE_PERM (
    ROLE_CD    VARCHAR2(30) NOT NULL,
    PERM_CD    VARCHAR2(50) NOT NULL,          -- {리소스}.{행위} 예: agent.read, person.rrn.decrypt
    CREATED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_ROLE_PERM PRIMARY KEY (ROLE_CD, PERM_CD),
    CONSTRAINT FK_ROLE_PERM_ROLE FOREIGN KEY (ROLE_CD) REFERENCES TB_ROLE(ROLE_CD)
);

COMMENT ON COLUMN TB_ROLE_PERM.PERM_CD IS '{리소스}.{행위} 형식 (설계서 10.1)';

-- Refresh 토큰 저장소.
-- 설계서 10.1은 "Refresh(14일, DB 저장·회전)"을 요구하지만 6.3의 테이블 목록에 저장소가 없다.
-- 회전(rotation)을 하려면 발급된 토큰의 상태를 서버가 알아야 하므로 테이블을 추가한다.
-- 토큰 원문이 아니라 해시를 저장한다 — DB가 유출돼도 그 자체로는 재사용할 수 없어야 한다.
CREATE TABLE TB_AUTH_REFRESH_TOKEN (
    TOKEN_ID    NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    USER_ID     NUMBER       NOT NULL,
    TOKEN_HASH  VARCHAR2(64) NOT NULL,          -- SHA-256(refresh token)
    ISSUED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_AT  TIMESTAMP    NOT NULL,
    REVOKED_AT  TIMESTAMP,                      -- 회전·로그아웃으로 무효화된 시각
    CREATED_AT  TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY  VARCHAR2(50) NOT NULL,
    UPDATED_AT  TIMESTAMP,
    UPDATED_BY  VARCHAR2(50),
    CONSTRAINT UQ_REFRESH_TOKEN_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_REFRESH_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID)
);

COMMENT ON TABLE TB_AUTH_REFRESH_TOKEN IS 'Refresh 토큰 (설계서 10.1의 DB 저장·회전 요건. 6.3 목록에 없어 v1.1에서 추가)';

CREATE INDEX IX_REFRESH_TOKEN_USER ON TB_AUTH_REFRESH_TOKEN(USER_ID, EXPIRES_AT);

-- 개인정보 접근로그 (설계서 6.5, 10.2)
CREATE TABLE TB_PRIVACY_ACCESS_LOG (
    LOG_ID           NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    USER_ID          NUMBER        NOT NULL,
    TARGET_PERSON_ID NUMBER        NOT NULL,     -- TB_PERSON 참조. FK는 Phase 2에서 추가
    ACCESS_TYPE_CD   VARCHAR2(10)  NOT NULL,     -- CD:ACCESS_TYPE (VIEW/DECRYPT/EXPORT)
    ACCESS_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    MENU_OR_API      VARCHAR2(200) NOT NULL,
    CLIENT_IP        VARCHAR2(45),               -- IPv6 고려
    PURPOSE_TXT      VARCHAR2(400),              -- 복호화 시 사유 입력 필수 (10.2)
    CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(50)  NOT NULL,
    UPDATED_AT       TIMESTAMP,
    UPDATED_BY       VARCHAR2(50),
    CONSTRAINT FK_PRIVACY_LOG_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID)
);

COMMENT ON TABLE TB_PRIVACY_ACCESS_LOG IS '개인정보 조회 접근로그 (설계서 10.2). 월 단위 파티션 대상 — V90 참조';

CREATE INDEX IX_PRIVACY_LOG_TARGET ON TB_PRIVACY_ACCESS_LOG(TARGET_PERSON_ID, ACCESS_AT);
CREATE INDEX IX_PRIVACY_LOG_USER ON TB_PRIVACY_ACCESS_LOG(USER_ID, ACCESS_AT);

-- ── 기본 역할과 권한 (설계서 10.1) ────────────────────────────────────────

INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, DESC_TXT, CREATED_BY) VALUES ('HR_ADMIN',       '인사팀 담당자',   '본사 인사 운영', 'SYSTEM');
INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, DESC_TXT, CREATED_BY) VALUES ('SALES_ADMIN',    '영업관리 담당자', '설계사 채널 운영', 'SYSTEM');
INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, DESC_TXT, CREATED_BY) VALUES ('BRANCH_MANAGER', '지점장/영업소장', '소속 조직 트리 하위만 조회 가능', 'SYSTEM');
INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, DESC_TXT, CREATED_BY) VALUES ('SUPPORT_STAFF',  '영업지원 스탭',   '소속 조직 한정, 조회 위주', 'SYSTEM');
INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, DESC_TXT, CREATED_BY) VALUES ('SELF',           '본인',            '셀프서비스', 'SYSTEM');
INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, DESC_TXT, CREATED_BY) VALUES ('SYSTEM',         '연계 시스템',     '기계 계정', 'SYSTEM');
INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, DESC_TXT, CREATED_BY) VALUES ('IT_ADMIN',       '시스템 관리자',   'IT 운영', 'SYSTEM');

-- HR_ADMIN: 조직·인물·임직원 전권. 설계사는 조회만.
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('HR_ADMIN', 'org.read',   'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('HR_ADMIN', 'org.write',  'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('HR_ADMIN', 'person.read',  'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('HR_ADMIN', 'person.write', 'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('HR_ADMIN', 'person.rrn.decrypt', 'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('HR_ADMIN', 'employee.read',  'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('HR_ADMIN', 'employee.write', 'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('HR_ADMIN', 'agent.read',  'SYSTEM');

-- SALES_ADMIN: 설계사 전권. 임직원은 조회만.
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SALES_ADMIN', 'org.read',    'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SALES_ADMIN', 'person.read', 'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SALES_ADMIN', 'person.write','SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SALES_ADMIN', 'person.rrn.decrypt', 'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SALES_ADMIN', 'employee.read', 'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SALES_ADMIN', 'agent.read',  'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SALES_ADMIN', 'agent.write', 'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SALES_ADMIN', 'agent.appoint',   'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SALES_ADMIN', 'agent.terminate', 'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SALES_ADMIN', 'agent.sanction',  'SYSTEM');

-- BRANCH_MANAGER: 소속 조직 트리 하위만 (행 수준 통제는 OrgScopeFilter가 별도로 강제)
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('BRANCH_MANAGER', 'org.read',      'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('BRANCH_MANAGER', 'person.read',   'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('BRANCH_MANAGER', 'employee.read', 'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('BRANCH_MANAGER', 'agent.read',    'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('BRANCH_MANAGER', 'agent.write',   'SYSTEM');

-- SUPPORT_STAFF: 조회 위주
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SUPPORT_STAFF', 'org.read',    'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SUPPORT_STAFF', 'person.read', 'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SUPPORT_STAFF', 'agent.read',  'SYSTEM');

-- SELF: 본인 정보 조회
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SELF', 'self.read', 'SYSTEM');

-- SYSTEM: 연계 전용
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SYSTEM', 'sync.read',   'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('SYSTEM', 'sync.export', 'SYSTEM');

-- IT_ADMIN: 공통코드/정책/계정/권한 운영. 업무 데이터 권한은 주지 않는다.
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('IT_ADMIN', 'code.read',   'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('IT_ADMIN', 'code.write',  'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('IT_ADMIN', 'policy.read', 'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('IT_ADMIN', 'policy.write','SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('IT_ADMIN', 'user.read',   'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('IT_ADMIN', 'user.write',  'SYSTEM');
INSERT INTO TB_ROLE_PERM (ROLE_CD, PERM_CD, CREATED_BY) VALUES ('IT_ADMIN', 'privacy.log.read', 'SYSTEM');
