-- V5__utc_timestamp_defaults.sql — 시각 컬럼의 적재 기준을 UTC로 통일 (설계서 6.2)
--
-- 배경: 애플리케이션은 Instant를 UTC로 적재한다(hibernate.jdbc.time_zone=UTC).
-- 그런데 DDL 기본값 SYSTIMESTAMP는 'DB 호스트 타임존'을 따르므로, DB가 Asia/Seoul로 도는
-- 운영 환경에서는 시드·직접 INSERT 행만 KST로 들어가 앱 기록 행과 9시간 어긋난다.
-- 로컬 gvenzl 컨테이너가 UTC(+00:00)라 문제가 드러나지 않았을 뿐이다.
--
-- SYS_EXTRACT_UTC(SYSTIMESTAMP)는 호스트 타임존과 무관하게 항상 UTC를 준다.
--
-- 이 파일이 ALTER인 이유: V2~V4는 이미 적용·태깅(phase-1)된 마이그레이션이다.
-- 적용된 마이그레이션을 고치면 기존 DB에서 체크섬이 깨진다(설계서 13.1).

-- 공통코드 (V2)
ALTER TABLE TB_CD_GRP MODIFY (CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE TB_CD     MODIFY (CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));

-- 정책값 (V3)
ALTER TABLE TB_POLICY_CONFIG MODIFY (CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));

-- 계정/역할/권한 (V4)
ALTER TABLE TB_USER      MODIFY (CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE TB_ROLE      MODIFY (CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE TB_USER_ROLE MODIFY (CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE TB_ROLE_PERM MODIFY (CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));

ALTER TABLE TB_AUTH_REFRESH_TOKEN MODIFY (
    CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    ISSUED_AT  DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP)
);

ALTER TABLE TB_PRIVACY_ACCESS_LOG MODIFY (
    CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    ACCESS_AT  DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP)
);
