-- V6__org.sql — 조직 (설계서 6.4, 6.5)
--
-- 본사 조직(부·팀)과 영업 조직(지역단–지점–영업소)을 하나의 자기참조 계층으로 통합 관리한다.

CREATE TABLE TB_ORG (
    ORG_ID        NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    ORG_CD        VARCHAR2(10)  NOT NULL,          -- 업무키 (예: A0001)
    ORG_NM        VARCHAR2(100) NOT NULL,
    ORG_TYPE_CD   VARCHAR2(10)  NOT NULL,          -- CD:ORG_TYPE (HQ_DEPT/REGION/BRANCH/OFFICE)
    UP_ORG_ID     NUMBER,                          -- 자기참조. 루트는 NULL
    ORG_LVL       NUMBER(2)     NOT NULL,
    SORT_ORD      NUMBER(5)     DEFAULT 0 NOT NULL,
    VALID_FROM_DT DATE          NOT NULL,
    VALID_TO_DT   DATE          DEFAULT DATE '9999-12-31' NOT NULL,
    USE_YN        CHAR(1)       DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT UQ_ORG_CD UNIQUE (ORG_CD),
    CONSTRAINT FK_ORG_UP FOREIGN KEY (UP_ORG_ID) REFERENCES TB_ORG(ORG_ID),
    CONSTRAINT CK_ORG_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_ORG_PERIOD CHECK (VALID_FROM_DT <= VALID_TO_DT)
);

COMMENT ON TABLE TB_ORG IS '조직 마스터 (본사부서/지역단/지점/영업소 통합 계층)';
COMMENT ON COLUMN TB_ORG.ORG_LVL IS '계층 깊이. 루트=1';

CREATE INDEX IX_ORG_UP ON TB_ORG(UP_ORG_ID);
CREATE INDEX IX_ORG_TYPE ON TB_ORG(ORG_TYPE_CD, USE_YN);

-- 조직 개편 이력.
--
-- BEFORE_JSON/AFTER_JSON은 변경된 필드만이 아니라 '변경 후(전) 조직의 전체 상태'를 담는다
-- (설계서 6.6 v1.2). diff를 담으면 기준일자 시점 조회(GET /orgs/tree?asOfDate=)를 하려고
-- 최초 생성부터 diff를 재생해야 하는데, 전체 스냅샷이면 "조직별 EFFECTIVE_DT <= 기준일 중
-- 최신 1건"을 골라 AFTER_JSON에서 꺼내면 끝난다.
CREATE TABLE TB_ORG_HIST (
    ORG_HIST_ID    NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    ORG_ID         NUMBER       NOT NULL,
    CHANGE_TYPE_CD VARCHAR2(10) NOT NULL,          -- CD:ORG_CHANGE_TYPE (CREATE/RENAME/MOVE/CLOSE)
    BEFORE_JSON    CLOB CHECK (BEFORE_JSON IS NULL OR BEFORE_JSON IS JSON),
    AFTER_JSON     CLOB CHECK (AFTER_JSON IS NULL OR AFTER_JSON IS JSON),
    EFFECTIVE_DT   DATE         NOT NULL,
    RSN_TXT        VARCHAR2(400),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_ORG_HIST_ORG FOREIGN KEY (ORG_ID) REFERENCES TB_ORG(ORG_ID)
);

COMMENT ON TABLE TB_ORG_HIST IS '조직 개편 이력. AFTER_JSON은 변경 후 전체 스냅샷 (설계서 6.6)';
COMMENT ON COLUMN TB_ORG_HIST.AFTER_JSON IS '변경 후 조직 전체 상태. 시점 조회의 원천';

-- 시점 조회가 "조직별 EFFECTIVE_DT <= :asOf 중 최신 1건"을 찾는 형태라 이 순서가 맞다.
CREATE INDEX IX_ORG_HIST_ASOF ON TB_ORG_HIST(ORG_ID, EFFECTIVE_DT DESC);

-- 조직 변경 유형 공통코드
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY)
VALUES ('ORG_CHANGE_TYPE', '조직변경유형', '조직 개편 이력 구분 (설계서 6.5)', 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ORG_CHANGE_TYPE', 'CREATE', '신설',     1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ORG_CHANGE_TYPE', 'RENAME', '명칭변경', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ORG_CHANGE_TYPE', 'MOVE',   '이관',     3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('ORG_CHANGE_TYPE', 'CLOSE',  '폐지',     4, 'SYSTEM');
