-- V9__emp_record_card.sql — 인사기록카드 6종 (설계서 6.5)
--
-- 학력/경력/가족/자격증/교육/상벌. 전부 TB_EMP에 종속된 단순 이력이며 상태머신이 없다.
-- 발령과 달리 여기에는 규칙이 거의 없다 — 직원이 지워지지 않는 한 이 행들도 남는다.

CREATE TABLE TB_EMP_SCHOOL (
    SCHOOL_ID       NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    EMP_ID          NUMBER        NOT NULL,
    SCHOOL_NM       VARCHAR2(100) NOT NULL,
    MAJOR_NM        VARCHAR2(100),
    DEGREE_CD       VARCHAR2(30)  NOT NULL,        -- CD:DEGREE
    GRAD_DT         DATE,
    GRAD_STATUS_CD  VARCHAR2(30)  NOT NULL,        -- CD:GRAD_STATUS
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_EMP_SCHOOL_EMP FOREIGN KEY (EMP_ID) REFERENCES TB_EMP(EMP_ID)
);
COMMENT ON TABLE TB_EMP_SCHOOL IS '인사기록카드 — 학력';
CREATE INDEX IX_EMP_SCHOOL_EMP ON TB_EMP_SCHOOL(EMP_ID);

CREATE TABLE TB_EMP_CAREER (
    CAREER_ID    NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    EMP_ID       NUMBER        NOT NULL,
    COMPANY_NM   VARCHAR2(100) NOT NULL,
    DEPT_NM      VARCHAR2(100),
    POSITION_NM  VARCHAR2(50),
    JOIN_DT      DATE          NOT NULL,
    LEAVE_DT     DATE,
    JOB_DESC     VARCHAR2(400),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_EMP_CAREER_EMP FOREIGN KEY (EMP_ID) REFERENCES TB_EMP(EMP_ID),
    CONSTRAINT CK_EMP_CAREER_PERIOD CHECK (LEAVE_DT IS NULL OR JOIN_DT <= LEAVE_DT)
);
COMMENT ON TABLE TB_EMP_CAREER IS '인사기록카드 — 경력 (입사 전 타사 경력)';
CREATE INDEX IX_EMP_CAREER_EMP ON TB_EMP_CAREER(EMP_ID);

-- 가족 정보는 개인정보다. 생년월일까지만 담고 주민번호는 받지 않는다 —
-- 필요해지면 TB_PERSON을 거쳐야 한다 (설계서 5.2: 주민번호 원문은 TB_PERSON에만).
CREATE TABLE TB_EMP_FAMILY (
    FAMILY_ID   NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    EMP_ID      NUMBER       NOT NULL,
    RELATION_CD VARCHAR2(30) NOT NULL,             -- CD:FAMILY_RELATION
    FAMILY_NM   VARCHAR2(50) NOT NULL,
    BIRTH_DT    DATE,
    COHABIT_YN  CHAR(1)      DEFAULT 'N' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_EMP_FAMILY_EMP FOREIGN KEY (EMP_ID) REFERENCES TB_EMP(EMP_ID),
    CONSTRAINT CK_EMP_FAMILY_COHABIT CHECK (COHABIT_YN IN ('Y', 'N'))
);
COMMENT ON TABLE TB_EMP_FAMILY IS '인사기록카드 — 가족. 주민번호는 담지 않는다';
CREATE INDEX IX_EMP_FAMILY_EMP ON TB_EMP_FAMILY(EMP_ID);

CREATE TABLE TB_EMP_CERT (
    CERT_ID    NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    EMP_ID     NUMBER        NOT NULL,
    CERT_NM    VARCHAR2(100) NOT NULL,
    ISSUER_NM  VARCHAR2(100),
    CERT_NO    VARCHAR2(50),
    ACQUIRE_DT DATE          NOT NULL,
    EXPIRE_DT  DATE,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_EMP_CERT_EMP FOREIGN KEY (EMP_ID) REFERENCES TB_EMP(EMP_ID),
    CONSTRAINT CK_EMP_CERT_PERIOD CHECK (EXPIRE_DT IS NULL OR ACQUIRE_DT <= EXPIRE_DT)
);
COMMENT ON TABLE TB_EMP_CERT IS '인사기록카드 — 직원 보유 자격증. 설계사 판매자격(TB_AGENT_LICENSE)과 무관하다';
CREATE INDEX IX_EMP_CERT_EMP ON TB_EMP_CERT(EMP_ID);

CREATE TABLE TB_EMP_EDU (
    EMP_EDU_ID  NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    EMP_ID      NUMBER        NOT NULL,
    EDU_NM      VARCHAR2(100) NOT NULL,
    EDU_TYPE_CD VARCHAR2(30)  NOT NULL,            -- CD:EDU_TYPE
    START_DT    DATE          NOT NULL,
    END_DT      DATE          NOT NULL,
    EDU_HOURS   NUMBER(5, 1),
    RESULT_CD   VARCHAR2(30)  NOT NULL,            -- CD:EDU_RESULT
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_EMP_EDU_EMP FOREIGN KEY (EMP_ID) REFERENCES TB_EMP(EMP_ID),
    CONSTRAINT CK_EMP_EDU_PERIOD CHECK (START_DT <= END_DT)
);
COMMENT ON TABLE TB_EMP_EDU IS '인사기록카드 — 직원 교육 이수. 설계사 보수교육(TB_AGENT_EDU)과 별개다';
CREATE INDEX IX_EMP_EDU_EMP ON TB_EMP_EDU(EMP_ID);

CREATE TABLE TB_EMP_REWARD_PUNISH (
    RP_ID      NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    EMP_ID     NUMBER       NOT NULL,
    RP_TYPE_CD VARCHAR2(30) NOT NULL,              -- CD:RP_TYPE (REWARD/PUNISH)
    RP_CD      VARCHAR2(30) NOT NULL,              -- CD:RP_DETAIL
    RP_DT      DATE         NOT NULL,
    RSN_TXT    VARCHAR2(400),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_EMP_RP_EMP FOREIGN KEY (EMP_ID) REFERENCES TB_EMP(EMP_ID)
);
COMMENT ON TABLE TB_EMP_REWARD_PUNISH IS '인사기록카드 — 상벌. 설계사 제재(TB_AGENT_SANCTION)와 별개다';
CREATE INDEX IX_EMP_RP_EMP ON TB_EMP_REWARD_PUNISH(EMP_ID);

-- 인사기록카드용 공통코드
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('DEGREE',          '학위',       NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('GRAD_STATUS',     '졸업상태',   NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('FAMILY_RELATION', '가족관계',   NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('EDU_RESULT',      '교육이수결과', NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('RP_TYPE',         '상벌구분',   NULL, 'SYSTEM');
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM, DESC_TXT, CREATED_BY) VALUES ('RP_DETAIL',       '상벌내역',   NULL, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('DEGREE', 'HIGH_SCHOOL', '고등학교', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('DEGREE', 'ASSOCIATE',   '전문학사', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('DEGREE', 'BACHELOR',    '학사',     3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('DEGREE', 'MASTER',      '석사',     4, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('DEGREE', 'DOCTOR',      '박사',     5, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GRAD_STATUS', 'GRADUATED', '졸업', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GRAD_STATUS', 'ENROLLED',  '재학', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GRAD_STATUS', 'DROPPED',   '중퇴', 3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('GRAD_STATUS', 'EXPECTED',  '졸업예정', 4, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('FAMILY_RELATION', 'SPOUSE',  '배우자', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('FAMILY_RELATION', 'CHILD',   '자녀',   2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('FAMILY_RELATION', 'PARENT',  '부모',   3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('FAMILY_RELATION', 'SIBLING', '형제자매', 4, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EDU_RESULT', 'COMPLETED', '이수',   1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('EDU_RESULT', 'FAILED',    '미이수', 2, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('RP_TYPE', 'REWARD', '포상', 1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('RP_TYPE', 'PUNISH', '징계', 2, 'SYSTEM');

INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('RP_DETAIL', 'COMMENDATION', '표창',   1, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('RP_DETAIL', 'BONUS',        '포상금', 2, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('RP_DETAIL', 'WARNING',      '경고',   3, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('RP_DETAIL', 'REPRIMAND',    '견책',   4, 'SYSTEM');
INSERT INTO TB_CD (GRP_CD, CD, CD_NM, SORT_ORD, CREATED_BY) VALUES ('RP_DETAIL', 'SUSPENSION',   '정직',   5, 'SYSTEM');
